[package]
name = "stats_provider"
version = "0.8.2"
description = "A simple system stats event provider for Sketchybar."
edition = "2024"
build = "build.rs"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.5", features = ["derive"] }
fs2 = "0.4.3"
starship-battery = "0.11.1"
sysinfo = { version = "0.39.6", default-features = false, features = [
  "component",
  "disk",
  "network",
  "system",
] }
tokio = { version = "1", features = ["full"] }

[build-dependencies]
cc = "1.4"
